add check_python_package function

diff --git a/funcs b/funcs
--- a/funcs
+++ b/funcs
@@ -55,6 +55,19 @@ function check_tool_prerequisites {
 	done
 }
 
+# Check the python2/python3 package is installed or not
+#
+function check_python_package {
+	local PYTHON="python"
+	local MISSING=""
+	[ "true" == "${USING_PYTHON3}" ] && PYTHON="python3"
+	for p in "$@"; do
+		INFO "checking python package: $(LIGHT_GREEN ${p})"
+		${PYTHON} -c "import ${p}" 2>&1 > /dev/null
+		[ "0" != "$?" ] && ERR "missing ${p}, please use pip to install: pip install ${p}" && MISSING="${MISSING} $p"
+	done
+}
+
 
 function RUN_CMD_STREAMING {
 	INFO "$(PURPLE $@)"
