update check_python_package

diff --git a/funcs b/funcs
--- a/funcs
+++ b/funcs
@@ -59,12 +59,13 @@ function check_tool_prerequisites {
 #
 function check_python_package {
 	local PYTHON="python"
+	local PIP="pip"
 	local MISSING=""
-	[ "true" == "${USING_PYTHON3}" ] && PYTHON="python3"
+	[ "true" == "${USING_PYTHON3}" ] && PYTHON="python3" && PIP="pip3"
 	for p in "$@"; do
 		INFO "checking python package: $(LIGHT_GREEN ${p})"
 		${PYTHON} -c "import ${p}" 2>&1 > /dev/null
-		[ "0" != "$?" ] && ERR "missing ${p}, please use pip to install: pip install ${p}" && MISSING="${MISSING} $p"
+		[ "0" != "$?" ] && ERR "missing ${p}, please use pip to install: ${PIP} install ${p}" && MISSING="${MISSING} $p"
 	done
 	[ "" != "${MISSING}" ] && return 1
 	return 0
