add package prerequisite checking in mycli

diff --git a/tools/mycli b/tools/mycli
--- a/tools/mycli
+++ b/tools/mycli
@@ -49,7 +49,66 @@ function load_helper_script {
 }
 
 
+function fn_exist {
+	declare -f -F $1 > /dev/null
+	return $?
+}
+
+
+function check_script_prerequisites {
+	local PREREQUISITES="mycli_command_prerequisites"
+	fn_exist ${PREREQUISITES} || return 0
+
+	local MISSING=""
+	local TMP=$(mktemp /tmp/XXXXXX)
+	${PREREQUISITES} > ${TMP}
+
+	local PKGS=($(cat ${TMP} | grep -v "^python2:" | grep -v "^python3"))
+	for p in "${PKGS[@]}"; do
+		echo -en "checking $(YELLOW $p) in system directory ..."
+		[ "" == "$(which $p)" ] && echo -e " => missing $p, please install it" && MISSING="${MISSING} $p" && continue
+		echo ""
+	done
+
+	local PYTHON="python"
+	local PIP="pip"
+	local PY_PKGS=($(cat ${TMP} | grep "^python2:"))
+	for p in "${PY_PKGS[@]}"; do
+		local PACKAGE=$(echo $p | awk -F':' '{print $2}')
+		echo -en "checking $(YELLOW ${PACKAGE}) in python2 ..."
+		${PYTHON} -c "import ${PACKAGE}" > /dev/null 2>&1
+		[ "0" != "$?" ] && echo -e " => missing, please use pip to install: $(PURPLE ${PIP} install ${PACKAGE})" && MISSING="${MISSING} $p" && continue
+		echo ""
+	done
+
+	PYTHON="python3"
+	PIP="pip3"
+	PY_PKGS=($(cat ${TMP} | grep "^python3:"))
+	for p in "${PY_PKGS[@]}"; do
+		local PACKAGE=$(echo $p | awk -F':' '{print $2}')
+		echo -en "checking $(YELLOW ${PACKAGE}) in python3 ..."
+		${PYTHON} -c "import ${PACKAGE}" > /dev/null 2>&1
+		[ "0" != "$?" ] && echo -e " => missing, please use pip to install: $(PURPLE ${PIP} install ${PACKAGE})" && MISSING="${MISSING} $p" && continue
+		echo ""
+	done
+
+	[ "" != "${MISSING}" ] && exit 1
+	return 0
+}
+
+
+function run_script_pre {
+	check_script_prerequisites
+}
+
+
+function run_script_post {
+	return
+}
+
+
 function run_script {
+	local ENTRY="$(basename ${MYCLI})_command_entry"
 	local SCRIPT="${CLI_BIN_DIR}/${CLI_ENTRY_NAME}"
 	[ ! -f "${SCRIPT}" ] && ERR "missing ${SCRIPT}" && exit 1
 
@@ -58,6 +117,7 @@ function run_script {
 		# Re-initialize CLI_XXX variables because
 		# this subcommand is a symbolic link to
 		# other directories.
+		#
 		local CURRENT=$(pwd)
 		cd ${SCRIPT_DIR}
 		cd ..
@@ -71,14 +131,16 @@ function run_script {
 	local SCRIPT_HELPERS="${CLI_HELPER_DIR}/funcs"
 	[ -f "${SCRIPT_HELPERS}" ] && load_helper_script ${SCRIPT_HELPERS}
 
-	# Load the script and run it
+	# Load the script
 	#
-	local ENTRY="$(basename ${MYCLI})_command_entry"
 	source ${SCRIPT}
-	${ENTRY} $@
 
+	# Run it with all prerequisites.
+	#
+	run_script_pre && ${ENTRY} $@ && run_script_post
 	exit $?
 }
+
 
 function show_oneline_doc {
 	local SCRIPT=$1
@@ -131,6 +193,7 @@ function show_helps {
 	find ${CLI_BIN_DIR} -name "${CLI_NAME}_*" | xargs -I{} sh -c "readlink -f {}" | grep -v ${CLI_BIN_DIR} > ${TMP}
 	[ "0" == "$(cat ${TMP} | wc -l)" ] && rm -f ${TMP} && exit 0
 
+	rm -f ${TMP}
 	echo ""
 	echo -e "EXTRA"
 	BUILTIN=false list_commands ${CLI_BIN_DIR}
